name: Deploy Three Tier App to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: fresh-k8s-cluster
  AWS_ROLE_ARN: arn:aws:iam::791296380741:role/GitHubActionsEKSRole
  NAMESPACE: three-tier

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      # ---------------- CHECKOUT ----------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- AWS AUTH (OIDC) ----------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------------- KUBECTL SETUP ----------------
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          kubectl version --client


      # ---------------- KUBECONFIG ----------------
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      # ---------------- NAMESPACE ----------------
      - name: Create namespace if not exists
        run: |
          kubectl create namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -

      # ---------------- DATABASE ----------------
      - name: Deploy Database
        run: |
          kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/Database/

      # ---------------- BACKEND ----------------
      - name: Deploy Backend
        run: |
          kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/Backend/

      # ---------------- FRONTEND ----------------
      - name: Deploy Frontend
        run: |
          kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/Frontend/

      # ---------------- INGRESS ----------------
      - name: Deploy Ingress
        run: |
          kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/ingress.yaml

      # ---------------- VERIFY ----------------
      - name: Verify Deployment
        run: |
          kubectl get pods -n $NAMESPACE
          kubectl get svc -n $NAMESPACE
          kubectl get ingress -n $NAMESPACE
